client: retrieveencfileclient.c
	gcc -o client retrieveencfileclient.c
	./client

server: doencfileserver.c
	gcc -o server doencfileserver.c
	./server

clean:
	rm -f client server plaintext.enc.txt *.enc